version: '3.8'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.jenkins_master
    container_name: jenkins-master
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  jenkins-builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: jenkins-builder
    networks:
      - jenkins
    tty: true

volumes:
  jenkins_home:

networks:
  jenkins:

    
